apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-demo
  # namespace is not needed as it defaults to 'default'
  labels:
    app: python-app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app-demo
  template:
    metadata:
      labels:
        app: python-app-demo
    spec:
      containers:
      - name: python-app
        image: harithahari2420/python-pipeline-sample:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  # namespace is not needed as it defaults to 'default'
spec:
  type: LoadBalancer  # Updated to LoadBalancer
  selector:
    app: python-app-demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
